spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show_sql: true
    database-platform:
  h2:
    console.enabled: true